<a href="https://colab.research.google.com/github/Sowrove-Khan/Python_Programming/blob/main/Complete_Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy means Numerical Python


Advantages of NumPy Arrays:

1.Allaws several mathmatical operations

2.Faster operations

In [1]:
import numpy as np

List Vs NumPy -Time consumption

In [3]:
from time import process_time

Time taken by List

In [ ]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007504960000002114


Time taken by NumPy Array

In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00015549699999972688


Creating List & NumPy Array

In [8]:
#List [Values are separeted by chomma]

list1 = [1,2,3,4,5]
print(list1)
type(list1)


[1, 2, 3, 4, 5]


list

In [9]:
#NumPy array [Values are not separeted by chomma & ndarray means number of dimension]

np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [11]:
#Creating 1 dim array [Array.shape diye dimension check kora jai(5,->is 1 dim, 5columns )]

A1 = np.array([1,2,3,4,5])
print(A1)
A1.shape

[1 2 3 4 5]


(5,)

In [14]:
#Creating 2 dim array [Array.shape diye dimension check kora jai(2,4->is 2 dim, 2rows & 4columns)]

A2 = np.array([(1,2,3,4),(5,6,7,8)])
print(A2)
A2.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [15]:
#Data conversion [int to float]

A3 = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(A3)
A3.shape

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


(2, 4)

Initial Placeholders in NumPy Arrays

In [16]:
#Create a numpy array of zeros

Z1 = np.zeros((4,5))
print(Z1)
Z1.shape

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(4, 5)

In [17]:
#Create a numpy array of ones

Z2 = np.ones((4,5))
print(Z2)
Z2.shape

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


(4, 5)

In [18]:
#Create a numpy array of a particular value

Z3 = np.full((4,5),4)
print(Z3)
Z3.shape

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


(4, 5)

In [4]:
#Creating Identity matrix [np.eye]

I = np.eye(3)
print(I)
I.shape

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


(3, 3)

In [7]:
#Creating NumPy array with random values [values are decimal and always between 0 to 1]

R1 = np.random.random((3,3))
print(R1)

[[0.90744302 0.05279483 0.83159224]
 [0.83733803 0.28620238 0.39292499]
 [0.37106894 0.76567995 0.7041688 ]]


In [8]:
#Creating NumPy array with random integer values within specific range [Range(1 to 50), size(4,4)]

R2 = np.random.randint(1,50,(4,4))
print(R2)

[[ 9 29  9 33]
 [17 38 12  8]
 [20 24 10 17]
 [34 30 29 49]]


In [5]:
#Creating the array of evenly(here is 4)spaced values ---> Specifying the number of values(here is 6)

E1 = np.linspace(10,30,6)
print(E1)

[10. 14. 18. 22. 26. 30.]


In [7]:
#Creating the array of evenly(here is 5)spaced values ---> Specifying the step(here is 5)

E2 = np.arange(10,30,5)
print(E2)

[10 15 20 25]


In [8]:
#Convert a List to a NumPy array [using np.asarray(list_name)]

List2 = [1,2,3,4,5]
print(List2)

np_array1 = np.asarray(List2)
print(np_array1)
type(np_array1)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


numpy.ndarray

Analysing a NumPy array

In [12]:
A = np.random.randint(10,80,(5,5))
print(A)

#Check Number of Rows and Columns(here 5)
print(A.shape)

#Check Number of Dimensions(here 2D)
print(A.ndim)

#Check Number of Elements(here 25)
print(A.size)

#Check the data type of the values stored in the array(int64 means 64 bit integer type)
print(A.dtype)

[[60 74 39 52 23]
 [78 64 38 63 36]
 [25 33 74 29 12]
 [69 63 15 54 22]
 [48 16 23 61 30]]
(5, 5)
2
25
int64


Mathmatical Operations on a NP Array

In [18]:
#Concatinate Or Join

L1  = [1,2,3,4,5]
L2  = [6,7,8,9,10]
print(L1 + L2)

#Element Wise Operation on NumPy Array

npa1 = np.random.randint(0,10,(3,3))
print(npa1)
npa2 = np.random.randint(10,20,(3,3))
print(npa2)
print(npa1 + npa2) #Addition by element
print(npa1 - npa2) #Subtraction by element
print(npa1 * npa2) #Multiplication by element
print(npa1 / npa2) #Division by element


#Another Way

print(np.add(npa1,npa2)) #Addition by element
print(np.subtract(npa1,npa2)) #Subtraction by element
print(np.multiply(npa1,npa2)) #Multiplication by element
print(np.divide(npa1,npa2)) #Division by element

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[[3 7 8]
 [5 8 1]
 [9 1 9]]
[[12 10 16]
 [14 15 12]
 [19 19 10]]
[[15 17 24]
 [19 23 13]
 [28 20 19]]
[[ -9  -3  -8]
 [ -9  -7 -11]
 [-10 -18  -1]]
[[ 36  70 128]
 [ 70 120  12]
 [171  19  90]]
[[0.25       0.7        0.5       ]
 [0.35714286 0.53333333 0.08333333]
 [0.47368421 0.05263158 0.9       ]]
[[15 17 24]
 [19 23 13]
 [28 20 19]]
[[ -9  -3  -8]
 [ -9  -7 -11]
 [-10 -18  -1]]
[[ 36  70 128]
 [ 70 120  12]
 [171  19  90]]
[[0.25       0.7        0.5       ]
 [0.35714286 0.53333333 0.08333333]
 [0.47368421 0.05263158 0.9       ]]


Array Manipulation

In [22]:
Array = np.random.randint(0,10,(3,4))
print(Array)
print(Array.shape)

#Transpose of Array

Trans = np.transpose(Array)
print(Trans)
print(Trans.shape)

#Re-shaping a array

R = Array.reshape(4,3)
print(R)
print(R.shape)

[[5 5 9 4]
 [0 7 3 4]
 [6 4 8 7]]
(3, 4)
[[5 0 6]
 [5 7 4]
 [9 3 8]
 [4 4 7]]
(4, 3)
[[5 5 9]
 [4 0 7]
 [3 4 6]
 [4 8 7]]
(4, 3)
